name: Build a Docker image

inputs:
  tag:
    description: Tag for the built Docker image
    required: true

runs:
  using: "composite"
  steps:
    - name: Build the image itself
      shell: bash
      run: docker build -t ${{ inputs.tag }} -f docker/Dockerfile .
